bytecodealliance/ComponentizeJS

- EXAMPLE.md
The example workflow has changed, this updates the Wasmtime configurations to ones that will work with componentize.
Unfortunately the WASI bindings require an older version of preview2, so there is currently a WASI bindings failure on this pending to fix before we merge.
We either need to trawl through the release matrix to work this out, otherwise I can aim to get the latest preview2 update to componentize-js soon which should resolve this.
> docs: update example

- crates/spidermonkey-embedding-splicer/src/lib.rs
> Fix typo: bindary -> binary

- README.md
This commit updates the README with the pre-requisites needed in order to build the project locally.
cc/ @guybedford
> docs: Update contributing section with pre-requisites

- Cargo.lock
- Cargo.toml
- crates/spidermonkey-embedding-splicer/Cargo.toml
- crates/spidermonkey-embedding-splicer/src/bindgen.rs
- crates/spidermonkey-embedding-splicer/src/lib.rs
- test/test.js
Latest toolchain + WASI upgrade.
> deps: toolchain upgrade

- Cargo.lock
- Cargo.toml
- crates/spidermonkey-embedding-splicer/src/bindgen.rs
- package-lock.json
- package.json
- src/componentize.js
- test/cases/type-imports/source.js
- test/cases/type-imports/test.js
- test/cases/type-imports/wit/deps/b/b.wit
- test/cases/type-imports/wit/world.wit
- test/test.js
Resolves https://github.com/bytecodealliance/componentize-js/issues/38 supporting cross-package interface uses.
> Cross package type aliases

- Cargo.lock
- Cargo.toml
- Makefile
- crates/spidermonkey-embedding-splicer/src/bindgen.rs
- crates/spidermonkey-embedding-splicer/src/lib.rs
- example/Cargo.lock
- example/Cargo.toml
- example/src/main.rs
- package-lock.json
- package.json
- src/componentize.js
Upgrades to the latest Jco bindgen.
> toolchain: jco upgrade

- src/componentize.js
Fixes ComponentizeJS windows support when applying Wizering.
> fix: componentize windows support

- .gitmodules
- README.md
- package.json
- types.d.ts
Adds a type definition file for ComponentizeJS, and updates the submodule to latest.
Resolves #97.
> add types, readme fix, submodule update

- .github/workflows/main.yml
Updates to https://github.com/bytecodealliance/StarlingMonkey/commit/fa1247bf553470ff04ed9e9f45a0c17b426c7f7d.
> deps: latest StarlingMonkey

- crates/spidermonkey-embedding-splicer/src/bindgen.rs
This fixes an issue with treeshaking where references to local package interfaces were turning into package references, which were being tree-shaken despite being internal references.
Fixes a bug in Jco's test suite under the latest ComponentizeJS.
Should also resolve https://github.com/bytecodealliance/ComponentizeJS/issues/126.
> fix: treeshaking of local package references

- crates/spidermonkey-embedding-splicer/src/bindgen.rs
This fixes the resource tree-shaking to ensure we never tree-shake resources, the reason being that any imported or exported function might use an imported resource, and we need to explicitly determine that check in the tree-shaking algorithm to support resource tree-shaking. This is noted as a TODO further. // cc @karthik2804 @tschneidereit
> fix: resource tree-shaking

- Makefile
- README.md
- crates/spidermonkey-embedding-splicer/src/bindgen.rs
- crates/spidermonkey-embedding-splicer/src/splice.rs
- embedding/embedding.cpp
- embedding/embedding.h
- src/componentize.js
- test/builtins/console-object.js
- test/builtins/console-simple.js
- test/builtins/crypto-random-disabled.js
- test/builtins/crypto-random.js
- test/builtins/error-async.js
- test/builtins/error-sync.js
- test/builtins/fetch.js
- test/builtins/globals.js
- test/builtins/math-random-disabled.js
- test/builtins/math-random.js
- test/builtins/now-disabled.js
- test/builtins/now.js
- test/builtins/timeout-disabled.js
- test/test.js
Adds support for `fetch` by supporting asynchronous functions for defined internal functions being componentized and async function support runs the event loop to completion on each function call to get the promise completion.
> feat: support fetch via async functions

- .github/workflows/main.yml
- .gitignore
- Makefile
- example/componentize.js
- package.json
- src/componentize.js
- test/builtins/now-disabled.js
- test/test.js
- types.d.ts
closes #133 
I am not sure how we want to modify the tests, Do we want to run all the tests for the `weval` build as well? I am happy to update it as necessary.
> add option to enable weval

- src/componentize.js
- types.d.ts
> allow to optionally pass in host env to wizer/weval

- example/Cargo.lock
- example/Cargo.toml
- example/src/main.rs
- Upgrade async-std to 1.13.0
- Upgrade cap-std to 3.3.0
To test out this change I ran the three commands include in the README.
> feat(example): Upgrade to wasmtime 25.0.1

- CMakeLists.txt
- Makefile
- embedding/embedding.cpp
- embedding/embedding.h
- src/componentize.js
- test/builtins/performance-disabled.js
- test/builtins/performance.js
Adds support for the performance builtin when using clocks.
Resolves https://github.com/bytecodealliance/ComponentizeJS/issues/144.
> feat: performance builtin support

- crates/spidermonkey-embedding-splicer/src/lib.rs
- crates/spidermonkey-embedding-splicer/src/splice.rs
- crates/spidermonkey-embedding-splicer/src/stub_wasi.rs
- package-lock.json
- package.json
Updates to using all WASI@0.2.2 bindings based to https://github.com/bytecodealliance/StarlingMonkey/pull/174.
> deps: update to WASI@0.2.2

- package.json
- Added type declaration files to ensure they are shipped alongside the package.
- Adjusted the exports field in package.json to ensure TypeScript can properly resolve the types.
Fixes #160
> fix: typescript type of package

- crates/spidermonkey-embedding-splicer/src/stub_wasi.rs
Resolves https://github.com/bytecodealliance/ComponentizeJS/issues/159.
> fix: wasi-poll stubbing

- Cargo.lock
- Cargo.toml
- crates/spidermonkey-embedding-splicer/src/bindgen.rs
- crates/spidermonkey-embedding-splicer/src/lib.rs
- package.json
Updates to the latest Orca, Wasmtime and Jco toolchains.
> deps: update to latest Wasmtime@30 toolchain

- src/componentize.js
Pulls in https://github.com/bytecodealliance/StarlingMonkey/pull/231
> Update to latest StarlingMonkey

- .github/workflows/release.yml
> fix(ci): set latest release when creating GH release
