README.md, package-lock.json, package.json, src/componentize.js
Adds `JavaScript` and the `ComponentizeJS` strings to the producer metadata section of the output component.
Resolves https://github.com/bytecodealliance/componentize-js/issues/2.
=> feat: Producer metadata

package-lock.json, package.json
This PR adds the GitHub repository as a temporary (?) `homepage` to `package.json` -- enabling `componentize-js` to have a link to the repo be shown on NPM.
Note that `package-lock.json` wasn't updated yet after the new version so that got pulled in too after `npm install`
=> chore: add repo as homepage to package.json

EXAMPLE.md
I tried running the wasm component in a node environment & I received the following error without the addition of the package.json file in the *hello* folder.
```
import { getStdio as lowering10Callee, getDirectories as lowering11Callee } from '@bytecodealliance/preview2-shim/preopens';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1055:15)
at Module._compile (node:internal/modules/cjs/loader:1090:27)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
at Module.load (node:internal/modules/cjs/loader:1004:32)
at Function.Module._load (node:internal/modules/cjs/loader:839:12)
at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
at …
```
=> Update EXAMPLE.md to fix spelling issues & add a couple of steps

Cargo.toml, crates/spidermonkey-embedding-splicer/src/lib.rs, src/componentize.js, test/cases/import-func/foo.js, test/cases/import-func/foo1.js, test/cases/import-func/foo4.js, test/cases/import-func/test.js, test/cases/kebab-fn-impt/print.js, test/cases/kebab-fn-impt/source.js, test/cases/kebab-fn-impt/test.js, test/cases/kebab-fn-impt/world.wit, test/test.js
Fixes a bug with kebab function import handing - for some reason the test cases weren't already covering this case, and now they do. We need to convert the core component `$root` convention into the ESM conventions and handle this throughout the process.
=> fix: kebab import function handling

crates/spidermonkey-embedding-splicer/src/bindgen.rs, crates/spidermonkey-embedding-splicer/src/lib.rs
This refactor prepares the groundwork for resources by removing the wasmtime-environ dependency. Turns out there was still a bunch of unused code from that previous usage that wasn't fully removed. This still relies on `wasmtime_environ::StringEncoding` but the next jco release will upgrade to no longer needing that as well.
=> refactor: remove wasmtime-environ usage

.prettierrc, Cargo.lock, README.md, crates/spidermonkey-embedding-splicer/src/lib.rs, crates/spidermonkey-embedding-splicer/src/splice.rs, crates/spidermonkey-embedding-splicer/src/stub_wasi.rs, crates/spidermonkey-embedding-splicer/wit/spidermonkey-embedding-splicer.wit, lib/exports/exports.d.ts, lib/spidermonkey-embedding-splicer.d.ts, lib/spidermonkey-embedding-splicer.js, src/componentize.js, test/test.js
This stubs out the unused WASI APIs used in Spidermonkey as they are mostly unused.
By default, this disables `console.log` from printing to stdout, with a new option, `enableStdout: bool` to reenable logging which then brings back in the WASI dependence. In future this should be using wasi logging directly.
=> WASI Stubs

crates/spidermonkey-embedding-splicer/src/bindgen.rs, package-lock.json, test/cases/versions/hello@1.0.0.js, test/cases/versions/hello@2.0.0.js, test/cases/versions/source.js, test/cases/versions/test.js, test/cases/versions/wit/deps/hello-1.0.0/hello.wit, test/cases/versions/wit/deps/hello-2.0.0/hello.wit, test/cases/versions/wit/world.wit
This adds support for importing and exporting versioned interfaces, including multiple versions of the "same" interface (where "same" means "has the same identifier, modulo version").
Note that we currently include the version number in JS identifiers unconditionally.  A future refinement would be to notice when only one version of a given interface is imported or exported and omit the version in that case.
Fixes #60
=> add support for WIT versions

Cargo.lock, Cargo.toml, crates/spidermonkey-embedding-splicer/src/splice.rs, spidermonkey_embedding/spidermonkey_embedding.cpp, test/cases/floats/floats.js, test/cases/floats/source.js, test/cases/floats/test.js, test/cases/floats/world.wit
Fixes https://github.com/bytecodealliance/componentize-js/issues/63.
Spidermonkey stores integer literals as integers, which we need to carefully detect when doing value parsing. This updates the float handling to detect the integer case properly and branch on the float conversion appropriately.
This affects both passed parameters and return values.
=> Fix: Floats Handling

Cargo.lock, Cargo.toml, crates/spidermonkey-embedding-splicer/src/bindgen.rs, test/cases/resource-borrow-import/source.js, test/cases/resource-borrow-import/test.js, test/cases/resource-borrow-import/world.wit
This provides partial support for #68.  I've focused on imported resources to begin with since APIs such as `wasi:http` make heavy use of child handles, which must be disposed in the correct order to avoid traps.
Supporting destructors for exported resources may also be useful, but not as urgent with respect to WASI.
=> support destructors for imported resources

Cargo.lock, Cargo.toml, lib/spidermonkey-embedding-splicer.js, package-lock.json, src/componentize.js, test/test.js
Updates to the latest bindgen crate. Currently against GitHub due to the patch required in https://github.com/bytecodealliance/jco/commit/e8781360cb29552ebd7ac116e64d8f4bd6ea7ab2.
=> deps: jco bindgen update

test/cases/resource-borrow-import/source.js, test/test.js
Fixes implicit drop support for borrows using the JCO PR in https://github.com/bytecodealliance/jco/pull/381.
Still on the GitHub reference for now until the next JCO release.
=> fix: drops for borrows

EXAMPLE.md, src/componentize.js
Corrects the `default` import code suggestion as outlined in resolves https://github.com/bytecodealliance/ComponentizeJS/issues/88.
The source name is separately fixed for Jco in https://github.com/bytecodealliance/jco/pull/388.
Documenting the componentize conventions will be a priority for stabilization, things may still be a little in flux for now.
=> fix: default code suggestion

.github/workflows/main.yml, .gitignore, .gitmodules, CMakeLists.txt, Cargo.toml, Makefile, crates/spidermonkey-embedding-splicer/src/bindgen.rs, crates/spidermonkey-embedding-splicer/src/lib.rs, crates/spidermonkey-embedding-splicer/src/splice.rs, embedding/embedding.cpp, embedding/embedding.h, example/Cargo.lock, example/Cargo.toml, example/src/main.rs, package-lock.json, package.json, rust-toolchain.toml, src/componentize.js, test/builtins/console-object.js
Updates ComponentizeJS to use the [StarlingMonkey engine base](https://github.com/fermyon/starlingMonkey) instead of Fastly's JS Compute Runtime shared builtins archive.
Based to the upstream PRs to StarlingMonkey at https://github.com/fermyon/StarlingMonkey/pull/11 and https://github.com/fermyon/StarlingMonkey/pull/12.
=> deps: use StarlingMonkey engine

crates/spidermonkey-embedding-splicer/src/lib.rs, crates/spidermonkey-embedding-splicer/src/stub_wasi.rs, crates/spidermonkey-embedding-splicer/wit/spidermonkey-embedding-splicer.wit, src/componentize.js
This PR makes sure that if an import is present in the target world, it does not get stubbed out. I went with a different approach than what was suggested in the [issue comment](https://github.com/bytecodealliance/ComponentizeJS/issues/105#issuecomment-2110865818) as I noticed the module only contained the wasi imports if they are a part of the target world and was simpler than having to prepare the `wit`. Let me know if I am missing something. 
fixes #105
=> do not stub imports that are part of the target world

.gitmodules
Update the submodule to point directly at the BA project instead of relying on GitHub redirects as there is now a fork in the `fermyon` org.
=> use the Bytecode Alliance org repository for StarlingMonkey

README.md, crates/spidermonkey-embedding-splicer/src/bindgen.rs, crates/spidermonkey-embedding-splicer/src/lib.rs, crates/spidermonkey-embedding-splicer/wit/spidermonkey-embedding-splicer.wit, package-lock.json, src/componentize.js
This PR adds the ability to use the `fetchEvent` from StarlingMonkey to handle incoming HTTP requests. This needs the `http` feature to be enabled explicitly.
=> allow  using fetchEvent for wasi:http/incoming-handler@0.2.0 optionally

embedding/embedding.cpp
This was disabled while doing testing for the `fetch` feature in https://github.com/bytecodealliance/ComponentizeJS/pull/131, but was left disabled by mistake.
=> fix: reenable free

src/componentize.js
This better supports creating and using the debug build, with the StarlingMonkey fix to keep the names section and providing a new configuration option for development workflows only.
=> fix: debug build

package.json
This commit adds the description field to ensure that componentize-js doesn't show HTML in NPM search.
e.g.
=> chore: add NPM description

src/componentize.js, types.d.ts
[This example](https://github.com/bytecodealliance/ComponentizeJS/blob/main/EXAMPLE.md) doesn’t currently work as the the code in [componentize.js](https://github.com/bytecodealliance/ComponentizeJS/blob/main/src/componentize.js) fails on this line https://github.com/bytecodealliance/ComponentizeJS/blob/d4ae59c16c0c5a781f3c4c18a4410a5fcf4e73a0/src/componentize.js#L50 because it can’t handle an undefined `opts`, even tho this should be allowed as suggested here https://github.com/bytecodealliance/ComponentizeJS/blob/d4ae59c16c0c5a781f3c4c18a4410a5fcf4e73a0/types.d.ts#L65 This PR should fix this.
I also allow the `env` field of `ComponentizeOptions` to be optional like all the others.
=> Handle undefined `opts` and allow undefined `env`

.github/workflows/main.yml, README.md, package.json, src/componentize.js, types.d.ts
This commit enables using a pre-existing `weval` binary -- this is mostly to try to avoid some flaky tests in `jco` downstream, but this is probably a reasonable thing to have in general. 
I also shuffled around some instructions/docs while I was in there.
=> feat: enable use of preexisting weval binary

crates/spidermonkey-embedding-splicer/src/lib.rs
Resolves https://github.com/bytecodealliance/ComponentizeJS/issues/166 ensuring we correctly reference the engine world when performing the world merging of the interfaces with the embedding.
=> fix: ensure correct reference to engine world in merge

src/componentize.js, test/cases/bad-binding/source.js, test/cases/bad-binding/test.js, test/cases/bad-binding/world.wit
This fixes an issue where we would incorrectly try to map `import.meta.url` due to not checking the import type.
Resolves https://github.com/bytecodealliance/ComponentizeJS/issues/164.
=> fix: specifier mappings in ComponentizeJS

README.md
It seems minor but I think it would be great if just copy-and-paste works.
=> fix: invalid usage example in README

.github/workflows/main.yml, Makefile, crates/spidermonkey-embedding-splicer/src/bindgen.rs, crates/spidermonkey-embedding-splicer/src/lib.rs, test/builtins/performance.js
Fixes the case where the guest wit states `wasi:http/incoming-handler@0.2.0` but the engine exports `wasi:http/incoming-handler@0.2.2`.
=> Allow to retain fetchEvent on all wasi 0.2.x versions

crates/spidermonkey-embedding-splicer/src/stub_wasi.rs
Specifically, without this patch WASIp2 imports where stubbed even if they are part of the target world, because of a bug in how the target world imports were checked.
Additionally, many WASIp1 imports where unconditionally stubbed, making it impossible to use them after resuming a wizer snapshot. With this commit, they're only stubbed if the respective WASIp2 functionality is stubbed as well.
Finally, ComponentizeJS now emits a warning for any imports that exist, but end up being stubbed. Without this, it's exceedingly difficult to debug why something doesn't work at runtime.
=> Fix issues with stubbing WASI imports

crates/spidermonkey-embedding-splicer/src/stub_wasi.rs
The warning added in #185 turns out to be too noisy: there are too many situations in which an import exists, but should be stubbed. In particular once StarlingMonkey is updated to include https://github.com/bytecodealliance/StarlingMonkey/pull/218, the warning would essentially be shown for every component, because in most cases, the target world won't contain the necessary interfaces, by design.
=> Remove warning about stubbed imports

src/componentize.js, types.d.ts
StarlingMonkey supports a growing number of arguments in addition to the filename of the script to run. This commit adds support for passing those arguments through when componentizing.
I think it'll eventually make sense to expose some of these arguments more explicitly, but providing this option allows us to evolve the interfaces separately, similar to how e.g. clang supports passing linker arguments, or cargo supports passing rustc arguments.
=> Support passing arguments to the StarlingMonkey runtime

.github/workflows/main.yml, Makefile, README.md, package-lock.json, package.json, src/componentize.js, test/builtins/performance.js, test/test.js, types.d.ts
This adds a new `debugBuild: true` option which when enabled uses the debug build that now correctly outputs the names section for Wasm stack traces in V8.
Because we don't currently support DWARF info through the V8 stacks, for now we strip all the debug info so we can still publish the debug build since it is only 13MB.
In future when we can work with the DWARF info, we can revisit this further, along with how the debug build is loaded.
Resolves #137.
=> feat: support the debugBuild option for debugging Wasm stacks

.gitignore, EXAMPLE.md, examples/hello-world/test.sh
Also, removed the hello.component.wasm from git since it is now ignored.
=> docs: fix the examples directory in EXAMPLE.md and .gitignore

crates/spidermonkey-embedding-splicer/src/splice.rs
This way, we don't have to update ComponentizeJS for any future minor versions.
=> Support all wasi-0.2.x patch versions in the splicer

types.d.ts
This PR adds the missing version export to the `types.d.ts` file.
=> add version export to types.d.ts

CMakeLists.txt, Makefile
This resolves https://github.com/bytecodealliance/ComponentizeJS/issues/199.
The debug build was not being picked up in the condition to be called `spidermonkey_embedding.debug.wasm` instead overwriting the release build.
=> fix: debug build output

src/componentize.js
This changes componentization to make paths relative to the current working directory. E.g. when componentizing `[project dir]/src/index.js`, instead of seeing that full path, content will now see `src/index.js`, because we preopen `[project dir]` as `/` and can thus treat all paths as relative to that.
This only works for Wizer, since Weval doesn't have a way to map directories in this way.
=> Don't expose absolute paths to source files

.github/workflows/main.yml, package-lock.json, package.json, src/componentize.js, test/cases/missing-export/test.js
This fixes a bug with the file paths not being passed through `maybeWindowsPath` for the initializer and the source directories. 
fixes #212
=> fix bug for file paths in windows during componentization

src/componentize.js, test/api/index.js, test/test.js
The new sytax uses cwd() to strip the prefix when building using original source location. We were not running it through maybeWindowsPath which led to file not being found during initialization. This PR fixes that and thus enables building on windows using the new syntax.
=> Fix building on windows when using new syntax

package-lock.json, src/componentize.js, src/platform.js, test/builtins/fetch.js, test/test.js, test/util.js
This test seems to be flaky in CI mostly because it relies on a remote URL.
What I'd *like* to do here is use a server that *we* manage (similar to how `jco` does, moving over some utility functions from there) that will definitely return JS, but it's not clear how the exported `source` was intended to be used (is it OK for that to become a function that takes a URL?).
In the meantime, we can at least retry the test while it depends on a remote URL (and we don't have any testing frameworks like `vitest` set up).
=> fix(ci): use a local test server for fetch test

.github/workflows/main.yml, Makefile, crates/spidermonkey-embedding-splicer/src/bindgen.rs, test/cases/http-server/source.js, test/cases/http-server/test.js, test/test.js, test/wit/test1.wit
This commit removes the ignored handling of `wasi:http/incoming-handler` which breaks components that have manually implemented the `handle` export.
This change was introduced during the [recent overhaul](https://github.com/bytecodealliance/ComponentizeJS/pull/202/files#diff-69c4ddcc3664701394605dc159a10360361dc21afeee1a01c967c1f06f1f967aR401), and I got blocked by this trying to upgrade [componentize-js in jco](https://github.com/bytecodealliance/jco/pull/620)
=> fix: do not skip wasi:http export processing

.github/workflows/release.yml
This commit adds the npmrc which utilizes the NPM token provided in CI secrets shortly before performing the NPM publish
=> fix(ci): add npmrc

.github/workflows/release.yml
This commit fixes the NPM publish to use the public access level (the default is private, which we don't use)
=> fix(ci): NPM public access release

.github/workflows/release.yml
While componentize-js packages can be now automatically released, the packages that come out of [the build](https://www.npmjs.com/package/@bytecodealliance/componentize-js/v/0.18.3-rc.3) are missing generated files and GHA attestations don't look like they're being recognized by NPM.
After "local" testing (via another repo), this commit addresses all the issues with the current release CI step. This commit:
- uses package-lock.json for runner cache
- removes a redundant release build
- enables attestation publishing for NPM
- uses more direct artifact name
- requires node version >= 22.x
=> fix(ci): npm release artifact

package.json
This commit adds repository.url which is required for build attestation
```
npm http fetch PUT 422 https://registry.npmjs.org/@bytecodealliance%2fcomponentize-js 7837ms
npm verbose stack HttpErrorGeneral: 422 Unprocessable Entity - PUT https://registry.npmjs.org/@bytecodealliance%2fcomponentize-js - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/bytecodealliance/ComponentizeJS" from provenance
npm verbose stack     at /opt/hostedtoolcache/node/22.16.0/x64/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:103:15
npm verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
npm verbose stack     at async publish …
```
=> fix: add repository.url to package.json

Makefile
This commit fixes the makefile splicer component deps to include the splicer-component Rust code. without this it was easy to build splicer components that didn't have *all* the latest code included.
This is also a part of #247 , but refactored out for easy merging
=> fix: makefile dep for splicer component

crates/spidermonkey-embedding-splicer/src/bindgen.rs, test/cases/http-request/source.js, test/cases/http-server/source.js
This commit fixes a regression in function generation when error handling is involved.
The buggy code over-eagerly checks whether there is an error type type present on a result, when there may legitimately not be (e.g. `result<t>` in WIT). The fix is to check *only* for whether the types are returned as a pair (indicating a `result`) at all.
=> fix: embedding splicer error handling

crates/spidermonkey-embedding-splicer/src/stub_wasi.rs
This commit fixes one bug and refactors the code to be more granular in the case of differing feature sets.
The reality is more nuanced -- as we must stub wasi:http/types differently depending on whether fetch-event is separately enabled.
Resolves #265
=> fix: logic for stubbing outgoing http and fetch-event

package-lock.json, package.json, test/builtins/performance.js, test/meta-resolve-stub.ts, test/test.js, test/vitest.ts
This PR moves us from `mocha` to `vitest` -- the diff is massive only because of `package-lock.json`, but checking the test output should be enough to confirm he functionality -- all tests are maintained (and now run in parallel) here and they all pass like before.
One thing that was weird is that `test:release` is evidently the exact same as `test`...
=> feat(tests): replace mocha with vitest

package-lock.json, package.json, test/builtins/fetch.js, test/cases/fetch-event-server/test.js, test/cases/http-server/test.js, test/util.js
This commit updates the tests that used `getRandomPort()` to perform their own random port getting and use the generated servers where appropriate, fixing a race condition on acquiring a temporary server port.
To be able to use `HTTPServer` instances with os-provided random ports from `@bytecodealliance/preview2-shim`, this PR updates updates the dev-dependency on preview2-shim to 0.17.4.
Resolves #287
=> fix(tests): race condition with server random port
